### ISSUE TITLE
README.md logo missing

### ISSUE THREAD

**Issue by cpswan** [atsign-foundation/docs#13]
**Describe the bug**

https://atsign.dev/assets/img/atPlatform_logo_gray.svg disappeared during the recent migration to a Gitbook generated site

**To Reproduce**
1. Browse to https://github.com/atsign-foundation/docs
2. See the missing logo

**Expected behavior**
Logo is shown (preferably in colours that match dark/light themes)

**Screenshots**

![image](https://github.com/atsign-foundation/docs/assets/478926/bb386b11-caa8-4bb4-9271-01b7a2e0fc7b)

**Comment by xavierchanth** [comment]
I think I'll have to make a manual list this time round... git-xargs did not pick up every repo clearly.

**Comment by cpswan** [comment]
This is also impacting the atsign-company READMEs etc.

![image](https://github.com/atsign-foundation/docs/assets/478926/bc009b63-ea40-48c7-b0fe-0a4837e0f109)

NB I've noticed we seem to be missing a `</h1>` closing tag on the logos line(s). It doesn't seem to be causing problems.

I've raised https://github.com/atsign-company/.github/pull/4 right away to fix the org profile
