### ISSUE TITLE
Publish Docs Site / Open Source the repo

### ISSUE THREAD

**Issue by XavierChanth** [atsign-foundation/docs#7]
The Gitbook site is already in a state where it is more contentful and up to date than the current docs.atsign.com repo.

It is also easier to maintain and keep up to date.

I think we should publish this site in PR 64

Blocked by:
```[tasklist]
### Tasks
- [ ] https://github.com/atsign-foundation/docs/issues/8
- [ ] https://github.com/atsign-foundation/docs/issues/3
```

**Comment by cpswan** [comment]
@XavierChanth I think this is done now, so closing. Feel free to reopen if I was wrong about that.
